INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Mary', 'Brown', 'Female', 24, 2022, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Jennifer', 'Taylor', 'Female', 18, 2023, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Elizabeth', 'Johnson', 'Female', 20, 2024, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Patricia', 'Johnson', 'Female', 18, 2020, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Robert', 'Smith', 'Male', 23, 2022, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Mary', 'Brown', 'Female', 23, 2024, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('James', 'Anderson', 'Male', 19, 2023, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Linda', 'Taylor', 'Female', 21, 2023, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Robert', 'Taylor', 'Male', 24, 2020, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Mary', 'Johnson', 'Female', 25, 2022, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('David', 'Taylor', 'Male', 25, 2020, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Mary', 'Smith', 'Female', 22, 2022, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Michael', 'Brown', 'Male', 25, 2022, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('David', 'Brown', 'Male', 25, 2022, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Michael', 'Anderson', 'Male', 25, 2023, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('David', 'Anderson', 'Male', 25, 2024, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('James', 'Smith', 'Male', 24, 2023, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Patricia', 'Anderson', 'Female', 25, 2024, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Michael', 'Johnson', 'Male', 23, 2020, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Jennifer', 'Taylor', 'Female', 18, 2024, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Mary', 'Smith', 'Female', 19, 2021, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Jennifer', 'Taylor', 'Female', 25, 2022, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Robert', 'Taylor', 'Male', 18, 2021, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('James', 'Brown', 'Male', 24, 2022, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Elizabeth', 'Smith', 'Female', 19, 2020, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Linda', 'Taylor', 'Female', 20, 2024, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('John', 'Brown', 'Male', 25, 2022, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Patricia', 'Anderson', 'Female', 21, 2021, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Mary', 'Smith', 'Female', 20, 2024, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('David', 'Smith', 'Male', 18, 2021, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Elizabeth', 'Taylor', 'Female', 18, 2021, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Robert', 'Smith', 'Male', 25, 2024, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('James', 'Anderson', 'Male', 25, 2023, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Linda', 'Johnson', 'Female', 22, 2021, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Patricia', 'Smith', 'Female', 19, 2024, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Michael', 'Smith', 'Male', 24, 2021, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Mary', 'Smith', 'Female', 24, 2020, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Michael', 'Johnson', 'Male', 19, 2022, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Michael', 'Johnson', 'Male', 22, 2020, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Linda', 'Smith', 'Female', 21, 2021, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Elizabeth', 'Johnson', 'Female', 25, 2021, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('James', 'Anderson', 'Male', 23, 2020, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('David', 'Taylor', 'Male', 23, 2023, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('James', 'Johnson', 'Male', 21, 2024, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Robert', 'Anderson', 'Male', 18, 2024, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('David', 'Taylor', 'Male', 23, 2024, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Elizabeth', 'Smith', 'Female', 20, 2021, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('James', 'Taylor', 'Male', 24, 2021, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('David', 'Johnson', 'Male', 24, 2023, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('David', 'Taylor', 'Male', 21, 2020, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('James', 'Brown', 'Male', 18, 2024, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Mary', 'Johnson', 'Female', 25, 2020, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Mary', 'Taylor', 'Female', 21, 2022, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('John', 'Smith', 'Male', 21, 2022, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Linda', 'Anderson', 'Female', 22, 2024, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Elizabeth', 'Smith', 'Female', 19, 2021, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Robert', 'Smith', 'Male', 23, 2021, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Michael', 'Taylor', 'Male', 25, 2021, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Robert', 'Anderson', 'Male', 20, 2023, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('John', 'Anderson', 'Male', 23, 2023, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Michael', 'Taylor', 'Male', 23, 2021, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Elizabeth', 'Smith', 'Female', 25, 2022, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Linda', 'Taylor', 'Female', 25, 2024, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Patricia', 'Taylor', 'Female', 20, 2020, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Elizabeth', 'Brown', 'Female', 20, 2021, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Patricia', 'Smith', 'Female', 25, 2021, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Patricia', 'Brown', 'Female', 21, 2022, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Michael', 'Anderson', 'Male', 22, 2022, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Mary', 'Smith', 'Female', 24, 2020, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Mary', 'Taylor', 'Female', 21, 2020, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('John', 'Johnson', 'Male', 20, 2024, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Elizabeth', 'Brown', 'Female', 21, 2023, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Jennifer', 'Brown', 'Female', 18, 2020, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Elizabeth', 'Taylor', 'Female', 23, 2020, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Linda', 'Smith', 'Female', 22, 2021, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('David', 'Johnson', 'Male', 24, 2021, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Robert', 'Anderson', 'Male', 20, 2023, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Mary', 'Smith', 'Female', 20, 2021, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Jennifer', 'Brown', 'Female', 23, 2023, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Jennifer', 'Anderson', 'Female', 21, 2020, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('James', 'Brown', 'Male', 21, 2023, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Patricia', 'Johnson', 'Female', 22, 2021, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Mary', 'Anderson', 'Female', 23, 2020, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Robert', 'Brown', 'Male', 23, 2020, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Jennifer', 'Anderson', 'Female', 19, 2023, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Patricia', 'Taylor', 'Female', 25, 2024, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Patricia', 'Taylor', 'Female', 24, 2023, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Linda', 'Anderson', 'Female', 22, 2020, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('John', 'Brown', 'Male', 20, 2021, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Jennifer', 'Brown', 'Female', 21, 2023, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('James', 'Taylor', 'Male', 22, 2020, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Robert', 'Johnson', 'Male', 22, 2023, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Mary', 'Brown', 'Female', 19, 2020, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Michael', 'Brown', 'Male', 24, 2024, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Michael', 'Johnson', 'Male', 24, 2023, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Elizabeth', 'Anderson', 'Female', 21, 2023, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('John', 'Brown', 'Male', 24, 2024, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Elizabeth', 'Brown', 'Female', 20, 2023, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Elizabeth', 'Taylor', 'Female', 21, 2024, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Robert', 'Anderson', 'Male', 19, 2021, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Jennifer', 'Johnson', 'Female', 18, 2020, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Linda', 'Smith', 'Female', 19, 2020, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Linda', 'Taylor', 'Female', 21, 2024, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Patricia', 'Taylor', 'Female', 20, 2020, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('David', 'Brown', 'Male', 18, 2024, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('David', 'Taylor', 'Male', 24, 2024, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Mary', 'Smith', 'Female', 23, 2023, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('David', 'Brown', 'Male', 24, 2021, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('David', 'Anderson', 'Male', 19, 2023, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Jennifer', 'Johnson', 'Female', 18, 2022, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Robert', 'Smith', 'Male', 25, 2023, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Michael', 'Johnson', 'Male', 20, 2020, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Michael', 'Johnson', 'Male', 23, 2022, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('John', 'Anderson', 'Male', 21, 2020, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('David', 'Taylor', 'Male', 21, 2024, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Michael', 'Johnson', 'Male', 25, 2021, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('David', 'Brown', 'Male', 24, 2020, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Robert', 'Johnson', 'Male', 24, 2022, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Robert', 'Smith', 'Male', 25, 2021, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Linda', 'Brown', 'Female', 20, 2023, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('James', 'Smith', 'Male', 18, 2024, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Robert', 'Smith', 'Male', 25, 2024, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Michael', 'Anderson', 'Male', 18, 2022, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Linda', 'Smith', 'Female', 18, 2020, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('John', 'Brown', 'Male', 19, 2021, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Robert', 'Anderson', 'Male', 21, 2023, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Jennifer', 'Brown', 'Female', 25, 2024, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Linda', 'Brown', 'Female', 21, 2024, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Michael', 'Taylor', 'Male', 20, 2020, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Linda', 'Taylor', 'Female', 24, 2024, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Robert', 'Smith', 'Male', 23, 2020, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Patricia', 'Brown', 'Female', 24, 2024, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Mary', 'Johnson', 'Female', 20, 2023, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Linda', 'Anderson', 'Female', 19, 2024, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('James', 'Smith', 'Male', 25, 2023, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Elizabeth', 'Anderson', 'Female', 23, 2023, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('John', 'Anderson', 'Male', 24, 2020, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Mary', 'Brown', 'Female', 23, 2020, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Mary', 'Johnson', 'Female', 19, 2021, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('David', 'Smith', 'Male', 20, 2022, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Mary', 'Smith', 'Female', 24, 2020, 'Engineering');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('James', 'Smith', 'Male', 23, 2024, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('John', 'Johnson', 'Male', 19, 2024, 'Mathematics');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Linda', 'Anderson', 'Female', 25, 2020, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Patricia', 'Brown', 'Female', 22, 2020, 'Computer Science');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('James', 'Johnson', 'Male', 20, 2021, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Michael', 'Johnson', 'Male', 21, 2021, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Robert', 'Johnson', 'Male', 20, 2023, 'History');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('Elizabeth', 'Smith', 'Female', 25, 2023, 'Biology');
INSERT INTO Students (FirstName, LastName, Gender, Age, EnrollmentYear, Major) VALUES ('John', 'Smith', 'Male', 24, 2023, 'Biology');
INSERT INTO Courses (CourseName, Department, Credits, Semester) VALUES ('Course 1', 'Engineering', 4, 'Summer 2024');
INSERT INTO Courses (CourseName, Department, Credits, Semester) VALUES ('Course 2', 'Computer Science', 3, 'Summer 2024');
INSERT INTO Courses (CourseName, Department, Credits, Semester) VALUES ('Course 3', 'Biology', 2, 'Spring 2024');
INSERT INTO Courses (CourseName, Department, Credits, Semester) VALUES ('Course 4', 'Mathematics', 3, 'Spring 2024');
INSERT INTO Courses (CourseName, Department, Credits, Semester) VALUES ('Course 5', 'Engineering', 2, 'Summer 2024');
INSERT INTO Courses (CourseName, Department, Credits, Semester) VALUES ('Course 6', 'Computer Science', 2, 'Spring 2024');
INSERT INTO Courses (CourseName, Department, Credits, Semester) VALUES ('Course 7', 'Engineering', 1, 'Summer 2024');
INSERT INTO Courses (CourseName, Department, Credits, Semester) VALUES ('Course 8', 'Biology', 1, 'Fall 2023');
INSERT INTO Courses (CourseName, Department, Credits, Semester) VALUES ('Course 9', 'Mathematics', 5, 'Spring 2024');
INSERT INTO Courses (CourseName, Department, Credits, Semester) VALUES ('Course 10', 'Mathematics', 4, 'Fall 2023');
INSERT INTO Courses (CourseName, Department, Credits, Semester) VALUES ('Course 11', 'Mathematics', 3, 'Fall 2023');
INSERT INTO Courses (CourseName, Department, Credits, Semester) VALUES ('Course 12', 'Engineering', 5, 'Spring 2024');
INSERT INTO Courses (CourseName, Department, Credits, Semester) VALUES ('Course 13', 'Biology', 3, 'Fall 2023');
INSERT INTO Courses (CourseName, Department, Credits, Semester) VALUES ('Course 14', 'Mathematics', 2, 'Spring 2024');
INSERT INTO Courses (CourseName, Department, Credits, Semester) VALUES ('Course 15', 'Computer Science', 3, 'Spring 2024');
INSERT INTO Courses (CourseName, Department, Credits, Semester) VALUES ('Course 16', 'Mathematics', 1, 'Spring 2024');
INSERT INTO Courses (CourseName, Department, Credits, Semester) VALUES ('Course 17', 'Mathematics', 3, 'Fall 2023');
INSERT INTO Courses (CourseName, Department, Credits, Semester) VALUES ('Course 18', 'Biology', 5, 'Summer 2024');
INSERT INTO Courses (CourseName, Department, Credits, Semester) VALUES ('Course 19', 'Mathematics', 4, 'Summer 2024');
INSERT INTO Courses (CourseName, Department, Credits, Semester) VALUES ('Course 20', 'Biology', 2, 'Fall 2023');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (87, 4, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (81, 11, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (2, 7, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (77, 12, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (7, 11, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (39, 20, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (121, 17, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (59, 13, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (24, 1, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (78, 4, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (145, 19, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (39, 11, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (124, 3, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (4, 15, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (97, 19, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (110, 16, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (121, 10, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (114, 10, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (109, 7, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (144, 5, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (51, 3, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (121, 17, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (51, 16, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (33, 1, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (56, 18, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (60, 2, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (97, 3, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (48, 18, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (68, 6, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (42, 19, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (3, 5, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (69, 2, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (5, 18, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (3, 15, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (9, 1, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (137, 16, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (123, 10, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (87, 3, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (39, 13, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (67, 5, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (140, 15, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (105, 19, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (149, 4, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (28, 1, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (57, 5, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (70, 18, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (95, 19, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (7, 9, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (50, 15, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (59, 3, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (76, 11, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (2, 14, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (53, 9, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (40, 10, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (50, 14, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (107, 19, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (60, 14, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (75, 9, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (72, 19, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (140, 7, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (15, 8, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (117, 1, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (12, 18, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (22, 8, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (46, 16, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (121, 9, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (85, 3, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (87, 3, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (9, 13, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (101, 20, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (103, 14, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (132, 3, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (136, 1, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (76, 17, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (15, 1, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (143, 10, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (109, 17, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (39, 3, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (107, 8, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (102, 18, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (24, 19, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (95, 7, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (71, 10, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (137, 11, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (139, 16, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (30, 16, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (44, 3, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (130, 14, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (103, 13, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (107, 1, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (93, 15, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (139, 15, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (81, 4, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (106, 1, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (96, 9, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (21, 18, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (120, 20, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (111, 7, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (55, 7, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (20, 1, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (65, 14, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (122, 1, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (5, 6, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (93, 15, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (72, 9, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (50, 7, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (40, 1, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (23, 2, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (19, 16, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (107, 14, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (11, 20, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (121, 14, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (36, 11, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (143, 18, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (43, 10, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (24, 5, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (61, 4, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (33, 6, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (60, 3, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (106, 7, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (121, 15, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (34, 1, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (84, 5, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (115, 8, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (74, 10, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (95, 13, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (15, 19, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (14, 13, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (3, 17, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (146, 6, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (12, 20, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (137, 13, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (14, 20, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (92, 17, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (63, 3, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (78, 11, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (17, 5, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (43, 13, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (69, 6, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (51, 2, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (141, 19, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (150, 2, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (65, 1, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (69, 14, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (34, 13, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (55, 16, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (64, 8, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (131, 1, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (68, 9, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (91, 2, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (91, 17, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (128, 19, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (112, 17, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (127, 20, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (89, 10, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (121, 9, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (82, 15, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (132, 6, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (124, 19, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (45, 2, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (10, 14, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (3, 2, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (45, 14, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (148, 2, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (54, 7, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (29, 8, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (137, 5, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (113, 9, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (57, 12, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (59, 16, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (62, 6, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (23, 10, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (89, 12, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (12, 11, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (55, 6, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (128, 13, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (139, 14, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (16, 7, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (135, 5, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (101, 3, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (111, 10, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (147, 8, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (87, 9, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (133, 14, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (14, 4, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (83, 9, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (82, 5, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (23, 4, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (122, 10, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (7, 11, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (80, 8, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (145, 16, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (71, 2, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (109, 13, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (147, 9, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (100, 10, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (16, 18, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (119, 10, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (12, 15, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (95, 4, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (32, 6, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (11, 1, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (63, 2, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (73, 8, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (132, 18, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (89, 20, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (132, 10, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (15, 10, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (94, 10, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (95, 18, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (88, 7, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (12, 3, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (19, 18, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (15, 17, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (85, 19, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (65, 20, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (79, 7, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (125, 10, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (34, 4, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (86, 12, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (14, 1, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (77, 3, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (5, 7, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (130, 16, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (129, 12, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (65, 6, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (126, 1, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (43, 6, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (129, 19, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (119, 1, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (12, 4, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (109, 20, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (87, 19, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (143, 1, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (69, 6, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (126, 5, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (5, 1, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (48, 8, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (30, 19, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (23, 7, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (119, 6, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (31, 8, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (23, 6, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (85, 16, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (103, 1, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (64, 3, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (19, 10, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (143, 17, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (79, 10, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (6, 6, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (111, 18, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (69, 20, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (117, 11, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (51, 6, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (24, 14, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (18, 10, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (144, 13, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (109, 12, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (74, 14, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (39, 3, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (19, 8, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (114, 3, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (77, 4, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (124, 8, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (42, 4, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (129, 5, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (43, 7, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (138, 16, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (28, 6, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (87, 19, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (35, 14, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (108, 18, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (119, 2, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (59, 14, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (103, 12, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (73, 19, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (5, 8, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (48, 14, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (44, 5, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (61, 7, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (57, 20, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (133, 5, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (75, 10, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (124, 20, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (108, 6, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (46, 11, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (131, 20, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (100, 2, 'B');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (13, 16, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (70, 16, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (11, 15, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (20, 15, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (149, 11, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (99, 10, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (133, 7, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (77, 18, 'D');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (49, 11, 'C');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (111, 13, 'F');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (126, 5, 'A');
INSERT INTO Enrollments (StudentID, CourseID, Grade) VALUES (82, 12, 'A');
